Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using ScheduleAutomation;
using ScheduleAutomation.Models;

namespace ScheduleAutomation.Controllers
{

    public class AdminController : Controller
    {
        private static string constr = ConfigurationManager.ConnectionStrings["Connection_ScheduleAutomationDB"].ConnectionString;

        private ScheduleAutomationEntities db = new ScheduleAutomationEntities();

        // GET: Admin
        public ActionResult Index()
        {
            var tblSessions = db.tblSessions.Include(t => t.tblCours);
            return View(tblSessions.ToList());
        }

        // GET: Admin/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSession tblSession = db.tblSessions.Find(id);
            if (tblSession == null)
            {
                return HttpNotFound();
            }
            return View(tblSession);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.tblCourses, "CourseID", "CourseCode");
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SessionID,sessionCode,sessionName,StartTime,EndTime,CourseID,SessionCreationDate,sessionStatus")] tblSession tblSession)
        {
            if (ModelState.IsValid)
            {
                tblSession.SessionID = Guid.NewGuid();
                db.tblSessions.Add(tblSession);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.tblCourses, "CourseID", "CourseCode", tblSession.CourseID);
            return View(tblSession);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSession tblSession = db.tblSessions.Find(id);
            if (tblSession == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.tblCourses, "CourseID", "CourseCode", tblSession.CourseID);
            return View(tblSession);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SessionID,sessionCode,sessionName,StartTime,EndTime,CourseID,SessionCreationDate,sessionStatus")] tblSession tblSession)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblSession).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.tblCourses, "CourseID", "CourseCode", tblSession.CourseID);
            return View(tblSession);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSession tblSession = db.tblSessions.Find(id);
            if (tblSession == null)
            {
                return HttpNotFound();
            }
            return View(tblSession);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            tblSession tblSession = db.tblSessions.Find(id);
            db.tblSessions.Remove(tblSession);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        #region Get Pending sessions for a Admin Home screen
        public JsonResult GetPendingSessionList()
        {

            List<AdminSessionListModel> pendingSessionList = new List<AdminSessionListModel>();

            //string query = @"select * 
            //                 from tblSession
            //                 where fk_statusID in ('1', '2') ";

            string query2 = @"SELECT tblSession.*, tblSessionStatus.statusLabel
                              FROM tblSession
                              INNER JOIN tblSessionStatus ON tblSession.fk_statusID=tblSessionStatus.statusID
                              Where tblSession.fk_statusID in (1,2);";

            //string constr = System.Configuration.ConfigurationManager.ConnectionStrings["ConString"].ConnectionString;
            //const string constr = @"Data source=L-PC176MXH\SQLEXPRESS;initial catalog=ScheduleAutomation;Integrated Security=SSPI;Pooling=False";

            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query2))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            var sessions = new AdminSessionListModel
                            {
                                sessionID = Guid.Parse(sdr["SessionID"].ToString()),
                                sessionCode = sdr["sessionCode"].ToString(),
                                sessionName = sdr["sessionName"].ToString(),
                                startTime = Convert.ToDateTime(sdr["StartTime"]),
                                endTime = Convert.ToDateTime(sdr["EndTime"]),
                                sessionStatus = sdr["statusLabel"].ToString(),
                                sessionCreationDate = Convert.ToDateTime(sdr["SessionCreationDate"]),
                            };

                            pendingSessionList.Add(sessions);

                        }
                        con.Close();
                        var json = JsonConvert.SerializeObject(pendingSessionList);
                        return Json(json, JsonRequestBehavior.AllowGet);
                    }
                }
            }

        }
        #endregion

        #region Get Completed sessions for a Admin Home screen
        public JsonResult GetCompletedSessionList()
        {

            List<AdminSessionListModel> completedSessionList = new List<AdminSessionListModel>();


            string query = @"SELECT tblSession.*, tblSessionStatus.statusLabel
                              FROM tblSession
                              INNER JOIN tblSessionStatus ON tblSession.fk_statusID=tblSessionStatus.statusID
                              Where tblSession.fk_statusID in (3);";

            //string constr = System.Configuration.ConfigurationManager.ConnectionStrings["ConString"].ConnectionString;
            //const string constr = @"Data source=L-PC176MXH\SQLEXPRESS;initial catalog=ScheduleAutomation;Integrated Security=SSPI;Pooling=False";

            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            var sessions = new AdminSessionListModel
                            {
                                sessionID = Guid.Parse(sdr["SessionID"].ToString()),
                                sessionCode = sdr["sessionCode"].ToString(),
                                sessionName = sdr["sessionName"].ToString(),
                                startTime = Convert.ToDateTime(sdr["StartTime"]),
                                endTime = Convert.ToDateTime(sdr["EndTime"]),
                                sessionStatus = sdr["statusLabel"].ToString(),
                                sessionCreationDate = Convert.ToDateTime(sdr["SessionCreationDate"]),
                            };

                            completedSessionList.Add(sessions);

                        }
                        con.Close();
                        var json = JsonConvert.SerializeObject(completedSessionList);
                        return Json(json, JsonRequestBehavior.AllowGet);
                    }
                }
            }

        }
        #endregion

        #region update session in database


        [HttpPost]
        public JsonResult updateSession(CellSessionListModel model)
        {
            updateSessionModel updatedSession = new updateSessionModel();
            updatedSession.sessionCode = model.sessionCode;
            updatedSession.sessionName = model.sessionName;
            updatedSession.StartTime = model.startTime;
            updatedSession.EndTime = model.endTime;
            updatedSession.SessionId = model.sessionID;
            int updatedsessionStatus = 3;

            string query = @"UPDATE tblSession 

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScheduleAutomation;

namespace ScheduleAutomation.Controllers
{
    public class RolesController : Controller
    {
        private ScheduleAutomationEntities db = new ScheduleAutomationEntities();

        // GET: Roles
        public ActionResult Index()
        {
            var tblRoles = db.tblRoles;
            return View(tblRoles.ToList());
        }

        //was used to get role details which is now not needed
        // GET: Roles/Details/5

        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    tblRole tblRole = db.tblRoles.Find(id);
        //    if (tblRole == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tblRole);
        //}

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoleID,Role")] tblRole tblRole)
        {
            if (ModelState.IsValid)
            {
                db.tblRoles.Add(tblRole);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblRole);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRole tblRole = db.tblRoles.Find(id);
            if (tblRole == null)
            {
                return HttpNotFound();
            }
            return View(tblRole);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoleID,Role")] tblRole tblRole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblRole).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblRole);
        }




        // GET: Roles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRole tblRole = db.tblRoles.Find(id);
            if (tblRole == null)
            {
                return HttpNotFound();
            }
            return View(tblRole);
        }




        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblRole tblRole = db.tblRoles.Find(id);
            db.tblRoles.Remove(tblRole);
            db.SaveChanges();

            return RedirectToAction("Index");
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.title</title>
    <link type="image/x-icon" rel="icon" href="~/Content/Images/CerLogo.png" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/Site.css" type="text/css" />
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" src="~/Scripts/Script.js"></script>



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>


    @* Navbar code *@
    <div id="header" class="navbarHeader">
        <nav class="myNavbar navbar navbar-static-top">
            <div class="navbar-nav">
                <ul id="navstylelinks">
                    <li>
                        <button id="SidebarOpen" class="SidebarOpen" onclick="openNav()">
                            <span>
                                <i id="sidebarRgt" class="fa fa-bars"></i>
                            </span>
                        </button>
                    </li>
                    <li>
                        <a href="@Url.Action("index","Home")" id="HomeIcon"><i class="fa fa-fw fa-home"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    @* Sidebar code *@
    <div id="mySidebar" class="sidebar">
        <a href="@Url.Action("index","Calendar")" class="Sidebarlink">Home</a>
        <a href="@Url.Action("index","Employee")" class="Sidebarlink">Employees</a>
        <a href="@Url.Action("index","Roles")" class="Sidebarlink">Roles</a>
        <a href="@Url.Action("index","Course")" class="Sidebarlink">Courses</a>
        <a href="@Url.Action("index","Session")" class="Sidebarlink">Sessions</a>
        <a href="@Url.Action("index","Admin")" class="Sidebarlink">Administrators</a>
    </div>

    <div class="container container-fluid">

        @RenderBody()

    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"></script>
    @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>*@
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">*@
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">*@
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <!--<div class="navbar-collapse collapse">-->
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("Employee", "Index", "Employee")</li>
            </ul>
            <!--</div>-->
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>