Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScheduleAutomation;
using ScheduleAutomation.Models;

namespace ScheduleAutomation.Controllers
{
    public class CourseController : Controller
    {
        private ScheduleAutomationEntities db = new ScheduleAutomationEntities();

        // GET: Course
        public ActionResult Index()
        {
            return View(db.tblCourses.ToList());
        }

        // GET: Course/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCourses tblCourses = db.tblCourses.Find(id);
            if (tblCourses == null)
            {
                return HttpNotFound();
            }
            return View(tblCourses);
        }


        //public ActionResult Session(Guid? id)
        //{
        //    List<tblSession> sessions = db.tblSessions.ToList();
        //    List<tblCourses> courses = db.tblCourses.ToList();
        //    List<string> container = new List<string>();

            
        //    foreach(var item in sessions)
        //    {

        //        if(item.CourseID == id)
        //        {
        //            container.Add(Convert.ToString(item.tblCours.CourseName));
        //            container.Add(Convert.ToString(item.SessionID));
        //            container.Add(Convert.ToString(item.sessionName));
        //            container.Add(Convert.ToString(item.StartTime));
        //            container.Add(Convert.ToString(item.EndTime));
        //        }

        //    }




        //    //if (id == null)
        //    //{
        //    //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    //}
        //    //tblSession tblSession = db.tblSessions.Find(id);
        //    //if (tblSession == null)
        //    //{
        //    //    return HttpNotFound();
        //    //}tblSession
        //    return View(container);
        //}





        // GET: Course/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Course/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,CourseCode,CourseName,CourseType,CourseLang")] tblCourses tblCourses)
        {
            if (ModelState.IsValid)
            {
                tblCourses.CourseID = Guid.NewGuid();
                db.tblCourses.Add(tblCourses);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblCourses);
        }

        // GET: Course/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCourses tblCourses = db.tblCourses.Find(id);
            if (tblCourses == null)
            {
                return HttpNotFound();
            }
            return View(tblCourses);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseID,CourseCode,CourseName,CourseType,CourseLang")] tblCourses tblCourses)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblCourses).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblCourses);
        }

        // GET: Course/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCourses tblCourses = db.tblCourses.Find(id);
            if (tblCourses == null)
            {
                return HttpNotFound();
            }
            return View(tblCourses);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            tblCourses tblCourses = db.tblCourses.Find(id);
            db.tblCourses.Remove(tblCourses);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScheduleAutomation;
using ScheduleAutomation.Models;

namespace ScheduleAutomation.Controllers
{
    public class SessionController : Controller
    {
        private ScheduleAutomationEntities db = new ScheduleAutomationEntities();

        // GET: Session
        public ActionResult Index()
        {
            var tblSessions = db.tblSessions.Include(t => t.tblCours);
            return View(tblSessions.ToList());
        }

        // GET: Session/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSession tblSession = db.tblSessions.Find(id);
            if (tblSession == null)
            {
                return HttpNotFound();
            }
            return View(tblSession);
        }





        // GET: Session/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.tblCourses, "CourseID", "CourseCode");
            return View();
        }

        // POST: Session/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SessionID,sessionCode,sessionName,StartTime,EndTime,CourseID")] tblSession tblSession)
        {
            if (ModelState.IsValid)
            {
                tblSession.SessionID = Guid.NewGuid();
                db.tblSessions.Add(tblSession);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.tblCourses, "CourseID", "CourseCode", tblSession.CourseID);
            return View(tblSession);
        }

        // GET: Session/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSession tblSession = db.tblSessions.Find(id);
            if (tblSession == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.tblCourses, "CourseID", "CourseCode", tblSession.CourseID);
            return View(tblSession);
        }

        // POST: Session/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SessionID,sessionCode,sessionName,StartTime,EndTime,CourseID")] tblSession tblSession)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblSession).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.tblCourses, "CourseID", "CourseCode", tblSession.CourseID);
            return View(tblSession);
        }

        // GET: Session/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSession tblSession = db.tblSessions.Find(id);
            if (tblSession == null)
            {
                return HttpNotFound();
            }
            return View(tblSession);
        }

        // POST: Session/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            tblSession tblSession = db.tblSessions.Find(id);
            db.tblSessions.Remove(tblSession);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Course/Create.cshtml
@model ScheduleAutomation.tblCourses

@{
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
    ViewBag.Title = "Create Course";
}

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

        <div class="courseCreateHeader">
            <h4 class="display-4">Create a new course here</h4>
            <hr />
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label col-md-2">Course Code</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Course Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Course Type</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Course Language</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseLang, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseLang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default createbtn" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        }

Views/Course/Delete.cshtml
@model ScheduleAutomation.tblCourses

@{
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
    ViewBag.Title = "Delete Course";
}

        <div class="courseDelHeader">
            <h3 class="display-4">Are you sure you want to delete this?</h3>
            <hr />
        </div>
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CourseCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourseCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CourseName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourseName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CourseType)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourseType)
                </dd>

                <dt>
                    Course Language
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourseLang)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default btn-danger" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>

Views/Course/Details.cshtml
@model ScheduleAutomation.tblCourses

@{
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
    ViewBag.Title = "Course details";
}
        <div class="courseDetailsHeader">
            <h4 class="display-4">View details of this course</h4>
            <hr />
        </div>
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CourseCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourseCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CourseName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourseName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CourseType)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourseType)
                </dd>

                <dt>
                    Course Language
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourseLang)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.CourseID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

Views/Course/Edit.cshtml
@model ScheduleAutomation.tblCourses

@{
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
    ViewBag.Title = "Edit Courses";
}

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

        <div class="courseEditHeader">
            <h4 class="display-4">Edit course details</h4>
            <hr />
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CourseID)

                <div class="form-group">
                    @Html.LabelFor(model => model.CourseCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CourseType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CourseLang, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseLang, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseLang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

Views/Course/Index.cshtml
@model IEnumerable<ScheduleAutomation.tblCourses>

@{
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
    ViewBag.Title = "Courses";
}


        <div class="create">
            <h1 class="display-4">Course section</h1>
            <a href="@Url.Action("Create","Course")" class="btn AddCourse"><img src="~/Content/Images/addCourse.png" class="addCourseimg" /><br />Add Course</a>
        </div>
        <div class="RoleList table-responsive">
            <h1 class="display-4">List of courses</h1>
            <table class="table  table-hover">
                <thead class="thead-light">
                    <tr>
                        <th>
                            Course Code
                        </th>
                        <th>
                            Course Name
                        </th>
                        <th>
                            Course Type
                        </th>
                        <th>
                            Course Language
                        </th>
                        <th></th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CourseCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CourseName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CourseType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CourseLang)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.CourseID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.CourseID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.CourseID }) | 
                            @Html.ActionLink("Sessions", "Session", new { id = item.CourseID })
                        </td>
                    </tr>
                }

            </table>
        </div>

Views/Course/Session.cshtml
@model IEnumerable<ScheduleAutomation.Models.SessionModel>
@using ScheduleAutomation.Models

@{
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
    ViewBag.Title = "Sessions";
}
<div class="container">

    <div class="create">
        <h1 class="display-4">All Sessions</h1>
        @*<a href="@Url.Action("Create","Session")" class="btn btn-primary"><br />Create Session</a>*@
    </div>


    <ul>
        @foreach (SessionModel sessionModel in Model)
        {
            <li>
                sessionModel.sessionName
            </li>
        }
    </ul>



























    @*<div class="table-responsive">
        <h1 class="display-4">List of sessions</h1>
        <table class="table  table-hover">
            <thead class="thead-light">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.sessionCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.sessionName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StartTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EndTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.tblCours.CourseCode)
                    </th>
                    <th></th>
                </tr>
            </thead>

            

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.sessionCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.sessionName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tblCours.CourseCode)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.SessionID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.SessionID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.SessionID })
                    </td>
                </tr>
            }

        </table>
    </div>*@













</div>